"""
Recommendation model - AI-powered personalized learning suggestions.

WHY: A beginner/intermediate developer needs guidance on WHAT to learn next.
This model stores personalized recommendations based on their learning history,
strengths, weaknesses, and goals across CP, DSA, Backend, and AI domains.

DESIGN: Recommendations are generated by AI analyzing user's entries,
patterns, and progress to suggest relevant resources, problems, and focus areas.
"""

import enum
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    Column, Integer, String, Text, DateTime, 
    Enum, Boolean, Float, JSON
)
from sqlalchemy.orm import relationship

from database import Base


class RecommendationType(enum.Enum):
    """
    Types of recommendations the system can generate.
    
    WHY: Different types serve different learning needs.
    """
    PROBLEM = "problem"              # Specific problem to solve (LeetCode, Codeforces)
    CONCEPT = "concept"              # Topic/concept to study
    RESOURCE = "resource"            # Article, video, course
    PRACTICE = "practice"            # Practice routine/approach
    REVISION = "revision"            # Review past struggles
    PROJECT = "project"              # Mini-project idea
    CHALLENGE = "challenge"          # Stretch goal/challenge


class RecommendationPriority(enum.Enum):
    """Priority levels for recommendations."""
    CRITICAL = "critical"      # Major weakness/gap
    HIGH = "high"              # Important for progress
    MEDIUM = "medium"          # Good to do
    LOW = "low"                # Nice to have


class RecommendationDomain(enum.Enum):
    """Domain areas for recommendations."""
    DSA = "dsa"                      # Data Structures & Algorithms
    CP = "cp"                        # Competitive Programming
    BACKEND = "backend"              # Backend Development
    AI_ML = "ai_ml"                  # AI/ML
    SYSTEM_DESIGN = "system_design"  # System Design
    GENERAL = "general"              # Cross-domain skills


class Recommendation(Base):
    """
    AI-generated personalized recommendation.
    
    WHY each field:
    - title: Quick summary of what's recommended
    - rec_type: Type of recommendation (problem, concept, etc.)
    - domain: Which area this belongs to
    - priority: How important based on user's gaps
    - reasoning: WHY this is recommended (key for learning)
    - resource_url: Link to problem/resource
    - estimated_time: How long it should take
    - is_completed: User marks when done
    - is_dismissed: User can skip irrelevant ones
    - feedback: User feedback for improving recommendations
    """
    __tablename__ = "recommendations"
    
    id = Column(Integer, primary_key=True, index=True)
    
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=False)
    rec_type = Column(Enum(RecommendationType), nullable=False, index=True)
    domain = Column(Enum(RecommendationDomain), nullable=False, index=True)
    priority = Column(Enum(RecommendationPriority), default=RecommendationPriority.MEDIUM)
    
    reasoning = Column(Text, nullable=False)
    
    resource_url = Column(String(2000), nullable=True)
    resource_name = Column(String(200), nullable=True)
    difficulty_level = Column(Integer, nullable=True)
    estimated_minutes = Column(Integer, nullable=True)
    
    related_patterns = Column(JSON, default=list)
    prerequisites = Column(JSON, default=list)
    
    is_completed = Column(Boolean, default=False, index=True)
    is_dismissed = Column(Boolean, default=False, index=True)
    completed_at = Column(DateTime, nullable=True)
    
    user_rating = Column(Integer, nullable=True)
    user_feedback = Column(Text, nullable=True)
    
    generated_by = Column(String(100), default="gemini")
    confidence_score = Column(Float, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)
    
    def __repr__(self):
        return f"<Recommendation(id={self.id}, title='{self.title}', type={self.rec_type.value})>"
